# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='post image'),
        ),
    ]
